stages:
  - build
  - deploy

variables:
  PROJECT_PATH: "/root/the-tip-top"

build:
  stage: build
  tags:
    - deploy
    - shell
  script:
    - cd $PROJECT_PATH/frontend
    - npm install
    - npm run build
    - cd $PROJECT_PATH/backend
    - npm install
    - npm run build
  only:
    - main

deploy:production:
  stage: deploy
  tags:
    - deploy
    - shell
  script:
    - cd $PROJECT_PATH
    - git pull origin main
    - cd frontend
    - npm run build
    - cd ../backend
    - npm run build
    - pm2 restart frontend
    - pm2 restart backend
    - echo "✅ Deployment completed successfully!"
  environment:
    name: production
    url: http://164.68.103.88
  only:
    - main
  when: manual
