stages:
  - build
  - deploy

variables:
  PROJECT_PATH: "/home/gitlab-runner/the-tip-top"

build:
  stage: build
  tags:
    - deploy
    - shell
  script:
    - git clone https://gitlab.com/MohaDjm/the-tip-top.git $PROJECT_PATH || true
    - cd $PROJECT_PATH
    - git pull origin main
    - cd frontend
    - npm install
    - npm run build
    - cd ../backend
    - npm install
    - npm run build
  only:
    - main

deploy:production:
  stage: deploy
  tags:
    - deploy
    - shell
  script:
    - cd $PROJECT_PATH
    - git pull origin main
    - cd frontend
    - npm run build
    - cd ../backend
    - npm run build
    - mkdir -p /var/www/the-tip-top/frontend/.next
    - mkdir -p /var/www/the-tip-top/backend/dist
    - mkdir -p /var/www/the-tip-top/frontend/src
    - mkdir -p /var/www/the-tip-top/backend/src
    - rsync -av --delete $PROJECT_PATH/frontend/.next/ /var/www/the-tip-top/frontend/.next/
    - rsync -av --delete $PROJECT_PATH/backend/dist/ /var/www/the-tip-top/backend/dist/
    - rsync -av --delete $PROJECT_PATH/frontend/src/ /var/www/the-tip-top/frontend/src/
    - rsync -av --delete $PROJECT_PATH/backend/src/ /var/www/the-tip-top/backend/src/
    - /usr/bin/pm2 restart frontend
    - /usr/bin/pm2 restart backend
    - echo "✅ Deployment completed successfully!"
  environment:
    name: production
    url: http://164.68.103.88
  only:
    - main
  # when: manual  # Déploiement automatique activé
