stages:
  - build
  - deploy

variables:
  PROJECT_PATH: "/home/gitlab-runner/the-tip-top"
  PRODUCTION_PATH: "/var/www/the-tip-top"

build:
  stage: build
  tags:
    - deploy
    - shell
  script:
    - git clone https://gitlab.com/MohaDjm/the-tip-top.git $PROJECT_PATH || true
    - cd $PROJECT_PATH
    - git pull origin main
    - cd frontend
    - npm install
    - npm run build
    - cd ../backend
    - npm install
    - npm run build
  only:
    - main

deploy:production:
  stage: deploy
  tags:
    - deploy
    - shell
  script:
    - cd $PROJECT_PATH
    - git pull origin main
    - cd frontend
    - npm run build
    - cd ../backend
    - npm run build
    # Fix permissions and clean old files
    - sudo rm -rf $PRODUCTION_PATH/frontend/.next
    - sudo rm -rf $PRODUCTION_PATH/backend/dist
    # Copy with sudo to handle permissions
    - sudo cp -r $PROJECT_PATH/frontend/.next $PRODUCTION_PATH/frontend/
    - sudo cp -r $PROJECT_PATH/backend/dist $PRODUCTION_PATH/backend/
    - sudo cp -r $PROJECT_PATH/frontend/src $PRODUCTION_PATH/frontend/
    - sudo cp -r $PROJECT_PATH/backend/src $PRODUCTION_PATH/backend/
    # Fix ownership after copy
    - sudo chown -R root:root $PRODUCTION_PATH/frontend/.next
    - sudo chown -R root:root $PRODUCTION_PATH/backend/dist
    - sudo pm2 restart backend
    - sudo pm2 restart frontend
    - echo "✅ Deployment completed successfully!"
  environment:
    name: production
    url: http://164.68.103.88
  only:
    - main
  # when: manual  # Déploiement automatique activé
